[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "F8o19NtvNsQMWqQDCu1WfYntrjooL8e11j8b7KjNTUtu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ouhuang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
